<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="raspbot_v2_like">

  <!-- Simple 4-wheel skid-steer robot (dimensions are approximate placeholders). -->
  <xacro:property name="chassis_length" value="0.32"/>
  <xacro:property name="chassis_width"  value="0.22"/>
  <xacro:property name="chassis_height" value="0.08"/>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width"  value="0.02"/>

  <xacro:property name="wheelbase" value="0.22"/> <!-- front/back separation -->
  <xacro:property name="track"     value="0.18"/> <!-- left/right separation -->

  <link name="base_link"/>

  <link name="chassis_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.0"/>
      <!-- Rough box inertia -->
      <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.03" iyz="0.0" izz="0.04"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${chassis_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.6 0.6 0.6 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2.0}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.2"/>
        <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0002"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 1.57079632679 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Front left/right -->
  <xacro:wheel name="front_left_wheel"  x="${ wheelbase/2.0}" y="${ track/2.0}"/>
  <xacro:wheel name="front_right_wheel" x="${ wheelbase/2.0}" y="${-track/2.0}"/>
  <!-- Rear left/right -->
  <xacro:wheel name="rear_left_wheel"   x="${-wheelbase/2.0}" y="${ track/2.0}"/>
  <xacro:wheel name="rear_right_wheel"  x="${-wheelbase/2.0}" y="${-track/2.0}"/>

</robot>

